/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/image`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/studentProfile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manageStudent` | `/manageStudent`; params?: Router.UnknownInputParams; } | { pathname: `/addStudent`; params?: Router.UnknownInputParams; } | { pathname: `/addAdmin`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/addStudent` | `/addStudent`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/attendanceList` | `/attendanceList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manageAdmins` | `/manageAdmins`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/image`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/studentProfile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/manageStudent` | `/manageStudent`; params?: Router.UnknownOutputParams; } | { pathname: `/addStudent`; params?: Router.UnknownOutputParams; } | { pathname: `/addAdmin`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/addStudent` | `/addStudent`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/attendanceList` | `/attendanceList`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/manageAdmins` | `/manageAdmins`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/dashboard${`?${string}` | `#${string}` | ''}` | `/image${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/studentProfile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/manageStudent${`?${string}` | `#${string}` | ''}` | `/manageStudent${`?${string}` | `#${string}` | ''}` | `/addStudent${`?${string}` | `#${string}` | ''}` | `/addAdmin${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/addStudent${`?${string}` | `#${string}` | ''}` | `/addStudent${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/attendanceList${`?${string}` | `#${string}` | ''}` | `/attendanceList${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/manageAdmins${`?${string}` | `#${string}` | ''}` | `/manageAdmins${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/image`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/studentProfile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manageStudent` | `/manageStudent`; params?: Router.UnknownInputParams; } | { pathname: `/addStudent`; params?: Router.UnknownInputParams; } | { pathname: `/addAdmin`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/addStudent` | `/addStudent`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/attendanceList` | `/attendanceList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manageAdmins` | `/manageAdmins`; params?: Router.UnknownInputParams; };
    }
  }
}
